### ISSUE TITLE
One element came above another one

### ISSUE THREAD

**Issue by RaminMammadzada** [digitekh2i/newsweek-bootstrap#2]
As it is seen in the screenshot below, an image came above another texts int the Subscribe section.
![image](https://user-images.githubusercontent.com/4702114/91055215-0761fb00-e62d-11ea-858c-ba5de607433d.png)

Reference in codebase: https://github.com/digitekh2i/newsweek-bootstrap/blob/9484549b557c81af1c0714cbec746bf9944475bc/index.html#L882

**Comment by digitekh2i** [comment]
Issue fixed.
Thank you very much
